"""initial portfolio cms schema

Revision ID: d9a6f32bce4c
Revises: 
Create Date: 2026-09-11 14:46:28.601078
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'd9a6f32bce4c'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('issuer', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('credential_id', sa.String(length=128), nullable=True),
    sa.Column('credential_url', sa.String(length=512), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('featured', sa.Boolean(), nullable=False),
    sa.Column('expiry_status', sa.Enum('ACTIVE', 'EXPIRED', 'NO_EXPIRY', name='certification_status', native_enum=False, length=16), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', name='content_status', native_enum=False, create_constraint=True, length=16), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_certifications'))
    )
    op.create_index(op.f('ix_certifications_status'), 'certifications', ['status'], unique=False)
    op.create_table('experience',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(length=180), nullable=False),
    sa.Column('role', sa.String(length=180), nullable=False),
    sa.Column('location', sa.String(length=128), nullable=True),
    sa.Column('employment_type', sa.String(length=64), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('highlights', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('technologies', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('visible', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_experience'))
    )
    op.create_index(op.f('ix_experience_visible'), 'experience', ['visible'], unique=False)
    op.create_table('media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('drive_file_id', sa.String(length=128), nullable=False),
    sa.Column('drive_folder_id', sa.String(length=128), nullable=True),
    sa.Column('category', sa.Enum('CV', 'PROFILE', 'PROJECT', 'CERTIFICATION', 'WRITEUP', 'EXPERIENCE', 'OTHER', name='media_category', native_enum=False, create_constraint=True, length=24), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=False),
    sa.Column('media_type', sa.Enum('IMAGE', 'VIDEO', 'PDF', 'DOCUMENT', 'OTHER', name='media_type', native_enum=False, create_constraint=True, length=16), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('drive_url', sa.String(length=1024), nullable=True),
    sa.Column('download_url', sa.String(length=1024), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=1024), nullable=True),
    sa.Column('access_policy', sa.Enum('PUBLIC', 'RESTRICTED', name='access_policy', native_enum=False, create_constraint=True, length=16), nullable=False),
    sa.Column('missing_in_drive', sa.Boolean(), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media'))
    )
    op.create_index(op.f('ix_media_category'), 'media', ['category'], unique=False)
    op.create_index(op.f('ix_media_checksum'), 'media', ['checksum'], unique=False)
    op.create_index(op.f('ix_media_drive_file_id'), 'media', ['drive_file_id'], unique=True)
    op.create_index(op.f('ix_media_drive_folder_id'), 'media', ['drive_folder_id'], unique=False)
    op.create_index(op.f('ix_media_media_type'), 'media', ['media_type'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('short_description', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('problem', sa.Text(), nullable=True),
    sa.Column('solution', sa.Text(), nullable=True),
    sa.Column('methodology', sa.Text(), nullable=True),
    sa.Column('technologies', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('security_focus', sa.String(length=128), nullable=True),
    sa.Column('vulnerability_type', sa.String(length=128), nullable=True),
    sa.Column('severity', sa.Enum('INFO', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severity', native_enum=False, create_constraint=True, length=16), nullable=True),
    sa.Column('cvss_score', sa.Float(), nullable=True),
    sa.Column('cwe', sa.String(length=32), nullable=True),
    sa.Column('owasp_category', sa.String(length=128), nullable=True),
    sa.Column('target_type', sa.String(length=64), nullable=True),
    sa.Column('testing_methodology', sa.Text(), nullable=True),
    sa.Column('tools_used', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('findings_summary', sa.Text(), nullable=True),
    sa.Column('remediation_summary', sa.Text(), nullable=True),
    sa.Column('github_url', sa.String(length=512), nullable=True),
    sa.Column('demo_url', sa.String(length=512), nullable=True),
    sa.Column('writeup_url', sa.String(length=512), nullable=True),
    sa.Column('featured', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', name='content_status', native_enum=False, create_constraint=True, length=16), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    op.create_index(op.f('ix_projects_category'), 'projects', ['category'], unique=False)
    op.create_index(op.f('ix_projects_featured'), 'projects', ['featured'], unique=False)
    op.create_index(op.f('ix_projects_slug'), 'projects', ['slug'], unique=True)
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'], unique=False)
    op.create_table('site_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_title', sa.String(length=180), nullable=False),
    sa.Column('seo_description', sa.Text(), nullable=True),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('og_title', sa.String(length=180), nullable=True),
    sa.Column('og_description', sa.Text(), nullable=True),
    sa.Column('og_image_url', sa.String(length=1024), nullable=True),
    sa.Column('canonical_url', sa.String(length=512), nullable=True),
    sa.Column('contact_email', sa.String(length=254), nullable=True),
    sa.Column('availability_status', sa.String(length=128), nullable=True),
    sa.Column('footer_text', sa.String(length=255), nullable=True),
    sa.Column('theme', sa.String(length=16), nullable=False),
    sa.Column('feature_flags', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_site_settings'))
    )
    op.create_table('skill_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('icon', sa.String(length=48), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skill_categories')),
    sa.UniqueConstraint('name', name=op.f('uq_skill_categories_name'))
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tags'))
    )
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('github_id', sa.Integer(), nullable=False),
    sa.Column('github_username', sa.String(length=64), nullable=False),
    sa.Column('github_avatar_url', sa.String(length=512), nullable=True),
    sa.Column('display_name', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'EDITOR', 'VIEWER', name='user_role', native_enum=False, create_constraint=True, length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_github_id'), 'users', ['github_id'], unique=True)
    op.create_index(op.f('ix_users_github_username'), 'users', ['github_username'], unique=False)
    op.create_table('writeups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=220), nullable=False),
    sa.Column('slug', sa.String(length=240), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('severity', sa.Enum('INFO', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severity', native_enum=False, create_constraint=True, length=16), nullable=True),
    sa.Column('cvss_score', sa.Float(), nullable=True),
    sa.Column('cwe', sa.String(length=32), nullable=True),
    sa.Column('owasp_category', sa.String(length=128), nullable=True),
    sa.Column('target_summary', sa.String(length=180), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', name='content_status', native_enum=False, create_constraint=True, length=16), nullable=False),
    sa.Column('featured', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reading_time_minutes', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_writeups'))
    )
    op.create_index(op.f('ix_writeups_category'), 'writeups', ['category'], unique=False)
    op.create_index(op.f('ix_writeups_slug'), 'writeups', ['slug'], unique=True)
    op.create_index(op.f('ix_writeups_status'), 'writeups', ['status'], unique=False)
    op.create_table('admin_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_admin_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admin_sessions')),
    sa.UniqueConstraint('session_token_hash', name=op.f('uq_admin_sessions_session_token_hash'))
    )
    op.create_index(op.f('ix_admin_sessions_user_id'), 'admin_sessions', ['user_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=48), nullable=True),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('request_id', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_request_id'), 'audit_logs', ['request_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('certification_media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('certification_id', sa.Integer(), nullable=False),
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.Column('caption', sa.String(length=255), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['certification_id'], ['certifications.id'], name=op.f('fk_certification_media_certification_id_certifications'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], name=op.f('fk_certification_media_media_id_media'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_certification_media')),
    sa.UniqueConstraint('certification_id', 'media_id', name='certification_media_unique')
    )
    op.create_index(op.f('ix_certification_media_certification_id'), 'certification_media', ['certification_id'], unique=False)
    op.create_index(op.f('ix_certification_media_media_id'), 'certification_media', ['media_id'], unique=False)
    op.create_table('content_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_type', sa.String(length=32), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=180), nullable=True),
    sa.Column('change_summary', sa.Text(), nullable=True),
    sa.Column('snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_content_versions_created_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_versions'))
    )
    op.create_index(op.f('ix_content_versions_resource_id'), 'content_versions', ['resource_id'], unique=False)
    op.create_index(op.f('ix_content_versions_resource_type'), 'content_versions', ['resource_type'], unique=False)
    op.create_table('cv_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.Column('version_name', sa.String(length=128), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], name=op.f('fk_cv_versions_media_id_media'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cv_versions'))
    )
    op.create_index(op.f('ix_cv_versions_is_current'), 'cv_versions', ['is_current'], unique=False)
    op.create_index(op.f('ix_cv_versions_media_id'), 'cv_versions', ['media_id'], unique=False)
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('headline', sa.String(length=255), nullable=True),
    sa.Column('short_bio', sa.Text(), nullable=True),
    sa.Column('long_bio', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=128), nullable=True),
    sa.Column('availability_status', sa.String(length=128), nullable=True),
    sa.Column('profile_image_media_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('phone', sa.String(length=48), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_image_media_id'], ['media.id'], name=op.f('fk_profile_profile_image_media_id_media'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profile'))
    )
    op.create_table('project_media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.Column('media_type', sa.Enum('IMAGE', 'VIDEO', 'PDF', 'DOCUMENT', 'OTHER', name='media_type', native_enum=False, create_constraint=True, length=16), nullable=False),
    sa.Column('caption', sa.String(length=255), nullable=True),
    sa.Column('alt_text', sa.String(length=255), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], name=op.f('fk_project_media_media_id_media'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_media_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_media')),
    sa.UniqueConstraint('project_id', 'media_id', name='project_media_unique')
    )
    op.create_index(op.f('ix_project_media_media_id'), 'project_media', ['media_id'], unique=False)
    op.create_index(op.f('ix_project_media_project_id'), 'project_media', ['project_id'], unique=False)
    op.create_table('project_tags',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_tags_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_project_tags_tag_id_tags'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'tag_id', name=op.f('pk_project_tags'))
    )
    op.create_table('skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=96), nullable=False),
    sa.Column('level', sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', 'EXPERT', name='skill_level', native_enum=False, create_constraint=True, length=16), nullable=False),
    sa.Column('icon', sa.String(length=48), nullable=True),
    sa.Column('featured', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['skill_categories.id'], name=op.f('fk_skills_category_id_skill_categories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skills')),
    sa.UniqueConstraint('category_id', 'name', name='skills_category_name_unique')
    )
    op.create_index(op.f('ix_skills_category_id'), 'skills', ['category_id'], unique=False)
    op.create_table('writeup_media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('writeup_id', sa.Integer(), nullable=False),
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.Column('caption', sa.String(length=255), nullable=True),
    sa.Column('alt_text', sa.String(length=255), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], name=op.f('fk_writeup_media_media_id_media'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['writeup_id'], ['writeups.id'], name=op.f('fk_writeup_media_writeup_id_writeups'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_writeup_media')),
    sa.UniqueConstraint('writeup_id', 'media_id', name='writeup_media_unique')
    )
    op.create_index(op.f('ix_writeup_media_media_id'), 'writeup_media', ['media_id'], unique=False)
    op.create_index(op.f('ix_writeup_media_writeup_id'), 'writeup_media', ['writeup_id'], unique=False)
    op.create_table('writeup_tags',
    sa.Column('writeup_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_writeup_tags_tag_id_tags'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['writeup_id'], ['writeups.id'], name=op.f('fk_writeup_tags_writeup_id_writeups'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('writeup_id', 'tag_id', name=op.f('pk_writeup_tags'))
    )
    op.create_table('social_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=48), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('icon', sa.String(length=48), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], name=op.f('fk_social_links_profile_id_profile'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_social_links'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('social_links')
    op.drop_table('writeup_tags')
    op.drop_index(op.f('ix_writeup_media_writeup_id'), table_name='writeup_media')
    op.drop_index(op.f('ix_writeup_media_media_id'), table_name='writeup_media')
    op.drop_table('writeup_media')
    op.drop_index(op.f('ix_skills_category_id'), table_name='skills')
    op.drop_table('skills')
    op.drop_table('project_tags')
    op.drop_index(op.f('ix_project_media_project_id'), table_name='project_media')
    op.drop_index(op.f('ix_project_media_media_id'), table_name='project_media')
    op.drop_table('project_media')
    op.drop_table('profile')
    op.drop_index(op.f('ix_cv_versions_media_id'), table_name='cv_versions')
    op.drop_index(op.f('ix_cv_versions_is_current'), table_name='cv_versions')
    op.drop_table('cv_versions')
    op.drop_index(op.f('ix_content_versions_resource_type'), table_name='content_versions')
    op.drop_index(op.f('ix_content_versions_resource_id'), table_name='content_versions')
    op.drop_table('content_versions')
    op.drop_index(op.f('ix_certification_media_media_id'), table_name='certification_media')
    op.drop_index(op.f('ix_certification_media_certification_id'), table_name='certification_media')
    op.drop_table('certification_media')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_request_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_admin_sessions_user_id'), table_name='admin_sessions')
    op.drop_table('admin_sessions')
    op.drop_index(op.f('ix_writeups_status'), table_name='writeups')
    op.drop_index(op.f('ix_writeups_slug'), table_name='writeups')
    op.drop_index(op.f('ix_writeups_category'), table_name='writeups')
    op.drop_table('writeups')
    op.drop_index(op.f('ix_users_github_username'), table_name='users')
    op.drop_index(op.f('ix_users_github_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_table('tags')
    op.drop_table('skill_categories')
    op.drop_table('site_settings')
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.drop_index(op.f('ix_projects_slug'), table_name='projects')
    op.drop_index(op.f('ix_projects_featured'), table_name='projects')
    op.drop_index(op.f('ix_projects_category'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_media_media_type'), table_name='media')
    op.drop_index(op.f('ix_media_drive_folder_id'), table_name='media')
    op.drop_index(op.f('ix_media_drive_file_id'), table_name='media')
    op.drop_index(op.f('ix_media_checksum'), table_name='media')
    op.drop_index(op.f('ix_media_category'), table_name='media')
    op.drop_table('media')
    op.drop_index(op.f('ix_experience_visible'), table_name='experience')
    op.drop_table('experience')
    op.drop_index(op.f('ix_certifications_status'), table_name='certifications')
    op.drop_table('certifications')
    # ### end Alembic commands ###
